const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,sort='score';
const lifecycle={new:'신규 포착',rising:'급상승',sustained:'지속',mainstream:'대중화',rebounding:'재부상',cooling:'둔화'};
const category={food_culinary:'음식·식품',seasonal_food_ritual:'음식·식품',music_performance:'음악',screen_content:'콘텐츠',gaming_digital:'게임',sports_participation:'스포츠',sports_attendance:'스포츠',place_experience:'여행·공간',lifestyle_behavior:'생활',product_brand:'제품·브랜드',technology_tool:'기술',fashion_collectible:'패션',unclassified:'기타'};
async function load(mode='demo'){const url=mode==='live'?'/api/v1/korea/curated-feed':'/api/v1/intelligence?at=2026-08-12T11:00:00%2B09:00&hours=168';data=await fetch(url).then(r=>r.json());$('#mode').textContent=`${data.mode} · ${data.window.from} ~ ${data.window.to} · ${data.unified_ranking.length}개 전체 항목`;render();renderIntegrations();}
function sortedRows(){const rows=[...data.unified_ranking];if(sort==='persistence')rows.sort((a,b)=>a.persistence_rank-b.persistence_rank);if(sort==='momentum')rows.sort((a,b)=>a.momentum_rank-b.momentum_rank);return rows;}
function render(){const rows=sortedRows();$('#laneTitle').textContent=`모든 트렌드 통합 전체 순위 (${rows.length}개, 제한 없음)`;$('#rankRows').innerHTML=rows.map((x,i)=>{const changes=Object.entries(x.rank_change_by_source||{}).map(([s,v])=>`${s==='google_trends'?'G':'X'} ${v==null?'신규':v>0?'▲'+v:v<0?'▼'+Math.abs(v):'―'}`).join(' · ');return `<tr data-topic="${esc(x.topic)}"><td>${i+1}<small>통합 ${x.rank}위</small></td><td><b>${esc(x.display_name||x.topic)}</b><small>원천: ${esc(x.raw_terms.join(', '))}</small></td><td>${esc(x.phenomenon_summary)}</td><td>${esc(x.classification)}</td><td><span class="life ${x.lifecycle}">${lifecycle[x.lifecycle]||x.lifecycle}</span><small>${esc(x.lifecycle_reason)}</small><small>신뢰도 ${esc(x.data_confidence?.label||'미확인')}</small></td><td>${esc(changes)}</td><td>${esc(category[x.category]||x.category)}</td><td>${x.score}</td><td>${x.latest_source_ranks.x??'—'}</td><td>${x.latest_source_ranks.google_trends??'—'}</td><td>${x.age_hours}시간<small>관측률 ${Math.round(x.persistence*100)}%</small></td><td>${esc(x.selection_reason)}</td></tr>`}).join('');$('#topicSelect').innerHTML=rows.map(x=>`<option value="${esc(x.topic)}">${esc(x.display_name||x.topic)}</option>`).join('');$('#topicSelect').onchange=()=>renderDetail(rows.find(x=>x.topic===$('#topicSelect').value));document.querySelectorAll('#rankRows tr').forEach(row=>row.onclick=()=>renderDetail(rows.find(x=>x.topic===row.dataset.topic)));renderDetail(rows[0]);}
function renderKeywords(items){$('#keywords').innerHTML=(items||[]).map(k=>`<span>${esc(k.text)}<small>${esc(k.status)}</small></span>`).join('')||'<span>관측·검토 키워드 없음</span>';}
async function loadObservedKeywords(x){try{const query=x.raw_terms[0]||x.topic;const r=await fetch(`/api/v1/keywords/x-related?query=${encodeURIComponent(query)}&topic=${encodeURIComponent(x.topic)}`).then(v=>v.json());if(r.status==='observed'){const merged=[...(r.keywords||[]),...(x.keywords||[])].filter((v,i,a)=>a.findIndex(z=>z.text.toLowerCase()===v.text.toLowerCase())===i).slice(0,5);renderKeywords(merged)}}catch{}}
function renderDetail(x){if(!x)return;$('#topicSelect').value=x.topic;renderKeywords(x.keywords);if(data.is_live)loadObservedKeywords(x);const recent=x.series.slice(-168),max=Math.max(...recent.map(p=>p.rank),1);$('#chart').innerHTML=recent.map(p=>`<i class="${p.source==='x'?'x':'google'}" title="${esc(p.at)} ${esc(p.source)} ${p.rank}위" style="height:${Math.max(5,(max-p.rank+1)/max*100)}%"></i>`).join('');$('#seriesSummary').textContent=`${x.display_name||x.topic} · ${x.phenomenon_summary} · 전체 ${x.series.length.toLocaleString()}개 관측값 · 최초 포착 후 ${x.age_hours}시간 · 지속기간순 ${x.persistence_rank}위 · 급상승순 ${x.momentum_rank}위`;$('#seriesRows').innerHTML=x.series.map(p=>`<tr><td>${new Date(p.at).toLocaleString('ko-KR')}</td><td>${p.source==='google_trends'?'Google Trends':'X'}</td><td>${p.rank}</td><td>${p.value}</td><td>${p.provenance==='generated'?'재구성':'실측'}</td></tr>`).join('');$('#companyRows').innerHTML=x.companies.length?x.companies.map(c=>`<tr><td>${esc(x.display_name||x.topic)}</td><td>${esc(c.relation_category)}</td><td>${esc(c.company)}</td><td>${c.stock_code??'비상장/해외'}</td><td>${esc(c.company_role)}</td><td>${esc(c.relation_tier_label)}</td><td>${esc(c.strength)}</td><td>${esc(c.verification_status)}</td><td>${esc(c.opportunity_status)}</td><td>${esc(c.reason)}<small>${esc(c.investment_warning)}</small></td><td>${c.stock_code?`<button class="verify-company" data-company="${esc(c.company)}" data-code="${c.stock_code}">기업정보 확인</button>`:esc(c.evidence_kind)}</td></tr>`).join(''):`<tr><td colspan="11">${esc(x.company_resolution.reason)}</td></tr>`;document.querySelectorAll('.verify-company').forEach(b=>b.onclick=()=>loadCompany(b.dataset.company,b.dataset.code));}
async function loadCompany(company,code){$('#companyProfile').textContent='불러오는 중';const p=await fetch(`/api/v1/companies/profile?company=${encodeURIComponent(company)}&stock_code=${code}`).then(r=>r.json());$('#companyProfile').textContent=JSON.stringify(p,null,2);}
async function renderIntegrations(){const s=await fetch('/api/v1/integrations').then(r=>r.json());$('#integrations').textContent=JSON.stringify(s,null,2);}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{sort=b.dataset.sort;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#demoMode').onclick=()=>load('demo');$('#liveMode').onclick=()=>load('live');load();
